### ISSUE TITLE
Provide last_touched ?? created_at

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/WebfactoryWfdMetaBundle#10]
@mpdude I want the Provider to provide me with the last_touched date or the created_at date, if there is noch last_touched date. Should I enhance the methods like [getLastTouchedOfEachRow](https://github.com/webfactory/WebfactoryWfdMetaBundle/blob/027cda156b7ad297ccbbc460ec53d0fc454d9845/Provider.php#L81) or should I implement new methods (BC)? I think this runs down to our definiton of "last touched".

**Comment by mpdude** [comment]
Strange. My assumption was that last_touched was updated whenever *anything* happens, including creation.

**Comment by MalteWunsch** [comment]
You were right. I misread lastmod_timestamp as last_touched. Haven't figured out what lastmod_timestamp actually is - do you know?
